# Generated by Django 6.0.5 on 2026-05-29 10:59

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('sap', 'SAP'), ('utility', 'Utility'), ('travel', 'Travel')], max_length=20)),
                ('original_filename', models.CharField(max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('row_count', models.IntegerField(default=0)),
                ('notes', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='HistoricalEmissionRecord',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('source', models.CharField(choices=[('sap', 'SAP'), ('utility', 'Utility'), ('travel', 'Travel')], max_length=20)),
                ('source_row_id', models.CharField(blank=True, help_text='Row identifier from the original file (e.g. SAP doc number)', max_length=100)),
                ('raw_data', models.JSONField(help_text='The original row as parsed from the file before any cleaning')),
                ('activity_date', models.DateField(blank=True, help_text='Normalised activity date (billing period start for utilities)', null=True)),
                ('period_end', models.DateField(blank=True, help_text='End of billing / activity period', null=True)),
                ('vendor_or_provider', models.CharField(blank=True, help_text='Supplier, utility company, airline, hotel, or taxi provider', max_length=255)),
                ('description', models.TextField(blank=True, help_text='Human-readable description of the activity')),
                ('quantity', models.FloatField(blank=True, help_text='Quantity in the normalised unit below', null=True)),
                ('unit', models.CharField(blank=True, choices=[('litres', 'Litres'), ('gallons', 'Gallons'), ('kwh', 'kWh'), ('km', 'Kilometres'), ('kg_co2e', 'kg CO₂e')], max_length=20)),
                ('raw_quantity', models.FloatField(blank=True, help_text='Original quantity before unit conversion', null=True)),
                ('raw_unit', models.CharField(blank=True, help_text='Original unit string from the source file', max_length=50)),
                ('co2e_kg', models.FloatField(blank=True, help_text='CO₂ equivalent in kg (calculated during parsing)', null=True)),
                ('emission_factor_used', models.FloatField(blank=True, help_text='Emission factor applied (kg CO₂e per unit)', null=True)),
                ('emission_factor_source', models.CharField(blank=True, help_text='Reference for the emission factor e.g. DEFRA 2023', max_length=255)),
                ('scope', models.CharField(blank=True, choices=[('scope1', 'Scope 1'), ('scope2', 'Scope 2'), ('scope3', 'Scope 3')], max_length=10)),
                ('origin_iata', models.CharField(blank=True, max_length=4)),
                ('destination_iata', models.CharField(blank=True, max_length=4)),
                ('distance_km', models.FloatField(blank=True, null=True)),
                ('travel_mode', models.CharField(blank=True, help_text='flight, hotel, taxi, etc.', max_length=50)),
                ('cost_amount', models.FloatField(blank=True, null=True)),
                ('cost_currency', models.CharField(blank=True, max_length=10)),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('analyst_note', models.TextField(blank=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('batch', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='emissions.uploadbatch')),
            ],
            options={
                'verbose_name': 'historical emission record',
                'verbose_name_plural': 'historical emission records',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='EmissionRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('sap', 'SAP'), ('utility', 'Utility'), ('travel', 'Travel')], max_length=20)),
                ('source_row_id', models.CharField(blank=True, help_text='Row identifier from the original file (e.g. SAP doc number)', max_length=100)),
                ('raw_data', models.JSONField(help_text='The original row as parsed from the file before any cleaning')),
                ('activity_date', models.DateField(blank=True, help_text='Normalised activity date (billing period start for utilities)', null=True)),
                ('period_end', models.DateField(blank=True, help_text='End of billing / activity period', null=True)),
                ('vendor_or_provider', models.CharField(blank=True, help_text='Supplier, utility company, airline, hotel, or taxi provider', max_length=255)),
                ('description', models.TextField(blank=True, help_text='Human-readable description of the activity')),
                ('quantity', models.FloatField(blank=True, help_text='Quantity in the normalised unit below', null=True)),
                ('unit', models.CharField(blank=True, choices=[('litres', 'Litres'), ('gallons', 'Gallons'), ('kwh', 'kWh'), ('km', 'Kilometres'), ('kg_co2e', 'kg CO₂e')], max_length=20)),
                ('raw_quantity', models.FloatField(blank=True, help_text='Original quantity before unit conversion', null=True)),
                ('raw_unit', models.CharField(blank=True, help_text='Original unit string from the source file', max_length=50)),
                ('co2e_kg', models.FloatField(blank=True, help_text='CO₂ equivalent in kg (calculated during parsing)', null=True)),
                ('emission_factor_used', models.FloatField(blank=True, help_text='Emission factor applied (kg CO₂e per unit)', null=True)),
                ('emission_factor_source', models.CharField(blank=True, help_text='Reference for the emission factor e.g. DEFRA 2023', max_length=255)),
                ('scope', models.CharField(blank=True, choices=[('scope1', 'Scope 1'), ('scope2', 'Scope 2'), ('scope3', 'Scope 3')], max_length=10)),
                ('origin_iata', models.CharField(blank=True, max_length=4)),
                ('destination_iata', models.CharField(blank=True, max_length=4)),
                ('distance_km', models.FloatField(blank=True, null=True)),
                ('travel_mode', models.CharField(blank=True, help_text='flight, hotel, taxi, etc.', max_length=50)),
                ('cost_amount', models.FloatField(blank=True, null=True)),
                ('cost_currency', models.CharField(blank=True, max_length=10)),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('analyst_note', models.TextField(blank=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='emissions.uploadbatch')),
            ],
            options={
                'ordering': ['-activity_date', '-created_at'],
                'indexes': [models.Index(fields=['source', 'status'], name='emissions_e_source_36b12e_idx'), models.Index(fields=['activity_date'], name='emissions_e_activit_c89ba8_idx'), models.Index(fields=['scope'], name='emissions_e_scope_63e497_idx')],
            },
        ),
    ]
